INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO unit_of_measures (description) VALUES ('Each');
INSERT INTO unit_of_measures (description) VALUES ('Dash');
INSERT INTO unit_of_measures (description) VALUES ('Teaspoon');
INSERT INTO unit_of_measures (description) VALUES ('Tablespoon');
INSERT INTO unit_of_measures (description) VALUES ('Cup');
INSERT INTO unit_of_measures (description) VALUES ('Pinch');
INSERT INTO unit_of_measures (description) VALUES ('Pint');
INSERT INTO unit_of_measures (description) VALUES ('Ounce');